services:
  db:
    # image: 'surrealdb/surrealdb:v2@sha256:1f78c443b0013774cf785785ca8e93c4213a8fdc4f638cb25643b06fac273627'
    image: 'surrealdb/surrealdb:nightly@sha256:37e8eb5dc50fb3574d50b89d90b9f30b560a6f490b74da1b8f86660994ff7820'
    container_name: netrondb
    volumes:
      - ./dbdata:/dbdata
    command:
      - start
      # - '--log'
      # - 'trace'
      - '--user'
      - ${SURREALDB_USER}
      - '--pass'
      - ${SURREALDB_PASS}
      - '--bind'
      - '0.0.0.0:8080'
      - 'surrealkv://dbdata'
    restart: always
  datafetcher:
    build:
      context: ./datafetcher
      dockerfile: Dockerfile
    environment:
      SOLANA_RPC: "${SOLANA_RPC}"
      SOLANA_SPLTOKEN_MINT_ADDRESS: "${SOLANA_SPLTOKEN_MINT_ADDRESS}"
      SURREALDB_HOST: "${SURREALDB_HOST}"
      SURREALDB_USER: "${SURREALDB_USER}"
      SURREALDB_PASS: "${SURREALDB_PASS}"
      SURREALDB_NS: "${SURREALDB_NS}"
      SURREALDB_DB: "${SURREALDB_DB}"
      BIRDEYE_KEY: "${BIRDEYE_KEY}"
      HELIUS_KEY: "${HELIUS_KEY}"
    links:
      - db
    restart: always
  t3:
    build:
      context: ./t3
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_SOLANA_RPC: "${NEXT_PUBLIC_SOLANA_RPC}"
        NEXT_PUBLIC_MAPBOX_KEY: "${NEXT_PUBLIC_MAPBOX_KEY}"
    environment:      
      DISCORD_CLIENT_ID: "${DISCORD_CLIENT_ID}"
      DISCORD_CLIENT_SECRET: "${DISCORD_CLIENT_SECRET}"
      NEXTAUTH_SECRET: "${NEXTAUTH_SECRET}"
      NEXTAUTH_URL: "${NEXTAUTH_URL}"
      SURREALDB_HOST: "${SURREALDB_HOST}"
      SURREALDB_USER: "${SURREALDB_USER}"
      SURREALDB_PASS: "${SURREALDB_PASS}"
      SURREALDB_NS: "${SURREALDB_NS}"
      SURREALDB_DB: "${SURREALDB_DB}"
    links:
      - db
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf