export const data = {
	currency: [
	{
		code: 'AC',
		currency_code: '?',
		currency_name: '?',
		currency_rate: 1,
		currency_symbol: '?',
		emoji: '🇦🇨',
		id: "country:AC",
		name: 'Ascension Island',
		price_pro: '100.00',
		price_std: '75.00',
		unicode: 'U+1F1E6 U+1F1E8'
	},
	{
		code: 'AD',
		currency_code: 'EUR',
		currency_name: 'Euro Member Countries',
		currency_rate: 0.050034445,
		currency_symbol: '€',
		emoji: '🇦🇩',
		id: "country:AD",
		name: 'Andorra',
		price_pro: '5.10',
		price_std: '3.75',
		unicode: 'U+1F1E6 U+1F1E9'
	},
	{
		code: 'AE',
		currency_code: 'AED',
		currency_name: 'Arab Emirates Dirham',
		currency_rate: 0.19937367,
		currency_symbol: 'DH',
		emoji: '🇦🇪',
		id: "country:AE",
		name: 'United Arab Emirates',
		price_pro: '19.94',
		price_std: '14.95',
		unicode: 'U+1F1E6 U+1F1EA'
	},
	{
		code: 'AF',
		currency_code: 'AFN',
		currency_name: 'Afghanistan Afghani',
		currency_rate: 3.90011391,
		currency_symbol: '؋',
		emoji: '🇦🇫',
		id: "country:AF",
		name: 'Afghanistan',
		price_pro: '390.01',
		price_std: '292.51',
		unicode: 'U+1F1E6 U+1F1EB'
	},
	{
		code: 'AG',
		currency_code: 'XCD',
		currency_name: 'East Caribbean Dollar',
		currency_rate: 0.14666974,
		currency_symbol: '$',
		emoji: '🇦🇬',
		id: "country:AG",
		name: 'Antigua & Barbuda',
		price_pro: '14.67',
		price_std: '11.00',
		unicode: 'U+1F1E6 U+1F1EC'
	},
	{
		code: 'AI',
		currency_code: 'XCD',
		currency_name: 'East Caribbean Dollar',
		currency_rate: 0.14666974,
		currency_symbol: '$',
		emoji: '🇦🇮',
		id: "country:AI",
		name: 'Anguilla',
		price_pro: '14.67',
		price_std: '11.00',
		unicode: 'U+1F1E6 U+1F1EE'
	},
	{
		code: 'AL',
		currency_code: '',
		currency_name: '',
		currency_rate: 1,
		currency_symbol: '',
		emoji: '🇦🇱',
		id: "country:AL",
		name: 'Albania',
		price_pro: '101.00',
		price_std: '76.00',
		unicode: 'U+1F1E6 U+1F1F1'
	},
	{
		code: 'AM',
		currency_code: 'AMD',
		currency_name: 'Armenian dram',
		currency_rate: 20.94378935,
		currency_symbol: '֏',
		emoji: '🇦🇲',
		id: "country:AM",
		name: 'Armenia',
		price_pro: '2094.38',
		price_std: '1570.78',
		unicode: 'U+1F1E6 U+1F1F2'
	},
	{
		code: 'AO',
		currency_code: 'AOA',
		currency_name: 'Angolan kwanza',
		currency_rate: 46.77255845,
		currency_symbol: 'Kz',
		emoji: '🇦🇴',
		id: "country:AO",
		name: 'Angola',
		price_pro: '4677.26',
		price_std: '3507.94',
		unicode: 'U+1F1E6 U+1F1F4'
	},
	{
		code: 'AQ',
		currency_code: '',
		currency_name: '',
		currency_rate: 1,
		currency_symbol: '',
		emoji: '🇦🇶',
		id: "country:AQ",
		name: 'Antarctica',
		price_pro: '100.00',
		price_std: '75.00',
		unicode: 'U+1F1E6 U+1F1F6'
	},
	{
		code: 'AR',
		currency_code: 'ARS',
		currency_name: 'Argentina Peso',
		currency_rate: 48.29018738,
		currency_symbol: '$',
		emoji: '🇦🇷',
		id: "country:AR",
		name: 'Argentina',
		price_pro: '4829.02',
		price_std: '3621.76',
		unicode: 'U+1F1E6 U+1F1F7'
	},
	{
		code: 'AS',
		currency_code: 'USD',
		currency_name: 'United States Dollar',
		currency_rate: 0.054288271,
		currency_symbol: '$',
		emoji: '🇦🇸',
		id: "country:AS",
		name: 'American Samoa',
		price_pro: '5.43',
		price_std: '4.07',
		unicode: 'U+1F1E6 U+1F1F8'
	},
	{
		code: 'AT',
		currency_code: 'EUR',
		currency_name: 'Euro Member Countries',
		currency_rate: 0.050034445,
		currency_symbol: '€',
		emoji: '🇦🇹',
		id: "country:AT",
		name: 'Austria',
		price_pro: '5.00',
		price_std: '3.75',
		unicode: 'U+1F1E6 U+1F1F9'
	},
	{
		code: 'AU',
		currency_code: 'AUD',
		currency_name: 'Australia Dollar',
		currency_rate: 0.08186056,
		currency_symbol: '$',
		emoji: '🇦🇺',
		id: "country:AU",
		name: 'Australia',
		price_pro: '8.19',
		price_std: '6.14',
		unicode: 'U+1F1E6 U+1F1FA'
	},
	{
		code: 'AW',
		currency_code: 'AWG',
		currency_name: 'Aruba Guilder',
		currency_rate: 0.097176005,
		currency_symbol: 'ƒ',
		emoji: '🇦🇼',
		id: "country:AW",
		name: 'Aruba',
		price_pro: '9.72',
		price_std: '7.29',
		unicode: 'U+1F1E6 U+1F1FC'
	},
	{
		code: 'AX',
		currency_code: 'EUR',
		currency_name: 'Euro Member Countries',
		currency_rate: 0.050034445,
		currency_symbol: '€',
		emoji: '🇦🇽',
		id: "country:AX",
		name: 'Åland Islands',
		price_pro: '5.00',
		price_std: '3.75',
		unicode: 'U+1F1E6 U+1F1FD'
	},
	{
		code: 'AZ',
		currency_code: 'AZN',
		currency_name: 'Azerbaijan Manat',
		currency_rate: 0.092286638,
		currency_symbol: '₼',
		emoji: '🇦🇿',
		id: "country:AZ",
		name: 'Azerbaijan',
		price_pro: '9.23',
		price_std: '6.92',
		unicode: 'U+1F1E6 U+1F1FF'
	},
	{
		code: 'BA',
		currency_code: 'BAM',
		currency_name: 'Bosnia and Herzegovina Convertible Mark',
		currency_rate: 0.097858869,
		currency_symbol: 'KM',
		emoji: '🇧🇦',
		id: "country:BA",
		name: 'Bosnia & Herzegovina',
		price_pro: '9.79',
		price_std: '7.34',
		unicode: 'U+1F1E7 U+1F1E6'
	},
	{
		code: 'BB',
		currency_code: 'BBD',
		currency_name: 'Barbados Dollar',
		currency_rate: 0.10857654,
		currency_symbol: '$',
		emoji: '🇧🇧',
		id: "country:BB",
		name: 'Barbados',
		price_pro: '10.86',
		price_std: '8.14',
		unicode: 'U+1F1E7 U+1F1E7'
	},
	{
		code: 'BD',
		currency_code: 'BDT',
		currency_name: 'Bangladeshi taka',
		currency_rate: 6.36595574,
		currency_symbol: '৳',
		emoji: '🇧🇩',
		id: "country:BD",
		name: 'Bangladesh',
		price_pro: '636.60',
		price_std: '477.45',
		unicode: 'U+1F1E7 U+1F1E9'
	},
	{
		code: 'BE',
		currency_code: 'EUR',
		currency_name: 'Euro Member Countries',
		currency_rate: 0.050034445,
		currency_symbol: '€',
		emoji: '🇧🇪',
		id: "country:BE",
		name: 'Belgium',
		price_pro: '5.00',
		price_std: '3.75',
		unicode: 'U+1F1E7 U+1F1EA'
	},
	{
		code: 'BF',
		currency_code: 'XOF',
		currency_name: 'West African CFA franc',
		currency_rate: 32.8204447,
		currency_symbol: 'F.CFA',
		emoji: '🇧🇫',
		id: "country:BF",
		name: 'Burkina Faso',
		price_pro: '3282.04',
		price_std: '2461.53',
		unicode: 'U+1F1E7 U+1F1EB'
	},
	{
		code: 'BG',
		currency_code: 'BGN',
		currency_name: 'Bulgaria Lev',
		currency_rate: 0.097858869,
		currency_symbol: 'лв',
		emoji: '🇧🇬',
		id: "country:BG",
		name: 'Bulgaria',
		price_pro: '9.79',
		price_std: '7.34',
		unicode: 'U+1F1E7 U+1F1EC'
	},
	{
		code: 'BH',
		currency_code: 'BHD',
		currency_name: 'Bahraini dinar',
		currency_rate: 0.02041239,
		currency_symbol: '.د.ب',
		emoji: '🇧🇭',
		id: "country:BH",
		name: 'Bahrain',
		price_pro: '2.04',
		price_std: '1.53',
		unicode: 'U+1F1E7 U+1F1ED'
	},
	{
		code: 'BI',
		currency_code: 'BIF',
		currency_name: 'Burundian franc',
		currency_rate: 156.21090204,
		currency_symbol: 'FBu',
		emoji: '🇧🇮',
		id: "country:BI",
		name: 'Burundi',
		price_pro: '15621.09',
		price_std: '11715.82',
		unicode: 'U+1F1E7 U+1F1EE'
	},
	{
		code: 'BJ',
		currency_code: 'XOF',
		currency_name: 'West African CFA franc',
		currency_rate: 32.8204447,
		currency_symbol: 'F.CFA',
		emoji: '🇧🇯',
		id: "country:BJ",
		name: 'Benin',
		price_pro: '3282.04',
		price_std: '2461.53',
		unicode: 'U+1F1E7 U+1F1EF'
	},
	{
		code: 'BL',
		currency_code: 'EUR',
		currency_name: 'Euro Member Countries',
		currency_rate: 0.050034445,
		currency_symbol: '€',
		emoji: '🇧🇱',
		id: "country:BL",
		name: 'St. Barthélemy',
		price_pro: '5.00',
		price_std: '3.75',
		unicode: 'U+1F1E7 U+1F1F1'
	},
	{
		code: 'BM',
		currency_code: 'BMD',
		currency_name: 'Bermuda Dollar',
		currency_rate: 0.054288271,
		currency_symbol: '$',
		emoji: '🇧🇲',
		id: "country:BM",
		name: 'Bermuda',
		price_pro: '5.43',
		price_std: '4.07',
		unicode: 'U+1F1E7 U+1F1F2'
	},
	{
		code: 'BN',
		currency_code: 'BND',
		currency_name: 'Brunei Darussalam Dollar',
		currency_rate: 0.073254401,
		currency_symbol: '$',
		emoji: '🇧🇳',
		id: "country:BN",
		name: 'Brunei',
		price_pro: '7.33',
		price_std: '5.49',
		unicode: 'U+1F1E7 U+1F1F3'
	},
	{
		code: 'BO',
		currency_code: 'BOB',
		currency_name: 'Bolivia Bolíviano',
		currency_rate: 0.37460436,
		currency_symbol: '$b',
		emoji: '🇧🇴',
		id: "country:BO",
		name: 'Bolivia',
		price_pro: '37.46',
		price_std: '28.10',
		unicode: 'U+1F1E7 U+1F1F4'
	},
	{
		code: 'BQ',
		currency_code: 'USD',
		currency_name: 'United States Dollar',
		currency_rate: 0.054288271,
		currency_symbol: '$',
		emoji: '🇧🇶',
		id: "country:BQ",
		name: 'Caribbean Netherlands',
		price_pro: '5.43',
		price_std: '4.07',
		unicode: 'U+1F1E7 U+1F1F6'
	},
	{
		code: 'BR',
		currency_code: 'BRL',
		currency_name: 'Brazil Real',
		currency_rate: 0.27987408,
		currency_symbol: 'R$',
		emoji: '🇧🇷',
		id: "country:BR",
		name: 'Brazil',
		price_pro: '27.99',
		price_std: '20.99',
		unicode: 'U+1F1E7 U+1F1F7'
	},
	{
		code: 'BS',
		currency_code: 'BSD',
		currency_name: 'Bahamas Dollar',
		currency_rate: 0.054288271,
		currency_symbol: '$',
		emoji: '🇧🇸',
		id: "country:BS",
		name: 'Bahamas',
		price_pro: '5.43',
		price_std: '4.07',
		unicode: 'U+1F1E7 U+1F1F8'
	},
	{
		code: 'BT',
		currency_code: 'BTN',
		currency_name: 'Bhutanese ngultrum',
		currency_rate: 4.50994852,
		currency_symbol: 'Nu.',
		emoji: '🇧🇹',
		id: "country:BT",
		name: 'Bhutan',
		price_pro: '450.99',
		price_std: '338.25',
		unicode: 'U+1F1E7 U+1F1F9'
	},
	{
		code: 'BV',
		currency_code: 'NOK',
		currency_name: 'Norway Krone',
		currency_rate: 0.57453922,
		currency_symbol: 'kr',
		emoji: '🇧🇻',
		id: "country:BV",
		name: 'Bouvet Island',
		price_pro: '57.45',
		price_std: '43.09',
		unicode: 'U+1F1E7 U+1F1FB'
	},
	{
		code: 'BW',
		currency_code: 'BWP',
		currency_name: 'Botswana Pula',
		currency_rate: 0.73730576,
		currency_symbol: 'P',
		emoji: '🇧🇼',
		id: "country:BW",
		name: 'Botswana',
		price_pro: '73.73',
		price_std: '55.30',
		unicode: 'U+1F1E7 U+1F1FC'
	},
	{
		code: 'BY',
		currency_code: 'BYN',
		currency_name: 'Belarus Ruble',
		currency_rate: 0.17752755,
		currency_symbol: 'Br',
		emoji: '🇧🇾',
		id: "country:BY",
		name: 'Belarus',
		price_pro: '17.75',
		price_std: '13.31',
		unicode: 'U+1F1E7 U+1F1FE'
	},
	{
		code: 'BZ',
		currency_code: 'BZD',
		currency_name: 'Belize Dollar',
		currency_rate: 0.10935999,
		currency_symbol: 'BZ$',
		emoji: '🇧🇿',
		id: "country:BZ",
		name: 'Belize',
		price_pro: '10.94',
		price_std: '8.20',
		unicode: 'U+1F1E7 U+1F1FF'
	},
	{
		code: 'CA',
		currency_code: 'CAD',
		currency_name: 'Canada Dollar',
		currency_rate: 0.074191953,
		currency_symbol: '$',
		emoji: '🇨🇦',
		id: "country:CA",
		name: 'Canada',
		price_pro: '7.42',
		price_std: '5.56',
		unicode: 'U+1F1E8 U+1F1E6'
	},
	{
		code: 'CC',
		currency_code: 'AUD',
		currency_name: 'Australia Dollar',
		currency_rate: 0.08186056,
		currency_symbol: '$',
		emoji: '🇨🇨',
		id: "country:CC",
		name: 'Cocos (Keeling) Islands',
		price_pro: '8.19',
		price_std: '6.14',
		unicode: 'U+1F1E8 U+1F1E8'
	},
	{
		code: 'CD',
		currency_code: 'CDF',
		currency_name: 'Congolese franc',
		currency_rate: 151.41466093,
		currency_symbol: 'FC',
		emoji: '🇨🇩',
		id: "country:CD",
		name: 'Congo - Kinshasa',
		price_pro: '15141.47',
		price_std: '11356.10',
		unicode: 'U+1F1E8 U+1F1E9'
	},
	{
		code: 'CF',
		currency_code: '',
		currency_name: '',
		currency_rate: 1,
		currency_symbol: '',
		emoji: '🇨🇫',
		id: "country:CF",
		name: 'Central African Republic',
		price_pro: '100.00',
		price_std: '75.00',
		unicode: 'U+1F1E8 U+1F1EB'
	},
	{
		code: 'CG',
		currency_code: '',
		currency_name: '',
		currency_rate: 1,
		currency_symbol: '',
		emoji: '🇨🇬',
		id: "country:CG",
		name: 'Congo - Brazzaville',
		price_pro: '100.00',
		price_std: '75.00',
		unicode: 'U+1F1E8 U+1F1EC'
	},
	{
		code: 'CH',
		currency_code: 'CHF',
		currency_name: 'Switzerland Franc',
		currency_rate: 0.049641764,
		currency_symbol: 'CHF',
		emoji: '🇨🇭',
		id: "country:CH",
		name: 'Switzerland',
		price_pro: '4.96',
		price_std: '3.72',
		unicode: 'U+1F1E8 U+1F1ED'
	},
	{
		code: 'CI',
		currency_code: 'XOF',
		currency_name: 'West African CFA franc',
		currency_rate: 32.8204447,
		currency_symbol: 'F.CFA',
		emoji: '🇨🇮',
		id: "country:CI",
		name: 'Côte d’Ivoire',
		price_pro: '3282.04',
		price_std: '2461.53',
		unicode: 'U+1F1E8 U+1F1EE'
	},
	{
		code: 'CK',
		currency_code: 'NZD',
		currency_name: 'New Zealand Dollar',
		currency_rate: 0.088598209,
		currency_symbol: '$',
		emoji: '🇨🇰',
		id: "country:CK",
		name: 'Cook Islands',
		price_pro: '8.86',
		price_std: '6.64',
		unicode: 'U+1F1E8 U+1F1F0'
	},
	{
		code: 'CL',
		currency_code: 'CLP',
		currency_name: 'Chile Peso',
		currency_rate: 49.31801619,
		currency_symbol: '$',
		emoji: '🇨🇱',
		id: "country:CL",
		name: 'Chile',
		price_pro: '4931.80',
		price_std: '3698.85',
		unicode: 'U+1F1E8 U+1F1F1'
	},
	{
		code: 'CM',
		currency_code: '',
		currency_name: '',
		currency_rate: 1,
		currency_symbol: '',
		emoji: '🇨🇲',
		id: "country:CM",
		name: 'Cameroon',
		price_pro: '100.00',
		price_std: '75.00',
		unicode: 'U+1F1E8 U+1F1F2'
	},
	{
		code: 'CN',
		currency_code: 'CNY',
		currency_name: 'China Yuan Renminbi',
		currency_rate: 0.39318772,
		currency_symbol: '¥',
		emoji: '🇨🇳',
		id: "country:CN",
		name: 'China',
		price_pro: '39.32',
		price_std: '29.49',
		unicode: 'U+1F1E8 U+1F1F3'
	},
	{
		code: 'CO',
		currency_code: 'COP',
		currency_name: 'Colombia Peso',
		currency_rate: 210.48264686,
		currency_symbol: '$',
		emoji: '🇨🇴',
		id: "country:CO",
		name: 'Colombia',
		price_pro: '21048.26',
		price_std: '15786.20',
		unicode: 'U+1F1E8 U+1F1F4'
	},
	{
		code: 'CP',
		currency_code: '?',
		currency_name: '?',
		currency_rate: 1,
		currency_symbol: '?',
		emoji: '🇨🇵',
		id: "country:CP",
		name: 'Clipperton Island',
		price_pro: '100.00',
		price_std: '75.00',
		unicode: 'U+1F1E8 U+1F1F5'
	},
	{
		code: 'CR',
		currency_code: 'CRC',
		currency_name: 'Costa Rica Colon',
		currency_rate: 27.96808413,
		currency_symbol: '₡',
		emoji: '🇨🇷',
		id: "country:CR",
		name: 'Costa Rica',
		price_pro: '2796.81',
		price_std: '2097.61',
		unicode: 'U+1F1E8 U+1F1F7'
	},
	{
		code: 'CU',
		currency_code: 'CUP',
		currency_name: 'Cuba Peso',
		currency_rate: 1.30145333,
		currency_symbol: '₱',
		emoji: '🇨🇺',
		id: "country:CU",
		name: 'Cuba',
		price_pro: '130.15',
		price_std: '97.61',
		unicode: 'U+1F1E8 U+1F1FA'
	},
	{
		code: 'CV',
		currency_code: 'CVE',
		currency_name: 'Cape Verdean escudo',
		currency_rate: 5.51729829,
		currency_symbol: '$',
		emoji: '🇨🇻',
		id: "country:CV",
		name: 'Cape Verde',
		price_pro: '551.73',
		price_std: '413.80',
		unicode: 'U+1F1E8 U+1F1FB'
	},
	{
		code: 'CW',
		currency_code: 'ANG',
		currency_name: 'Netherlands Antilles Guilder',
		currency_rate: 0.09729635,
		currency_symbol: 'ƒ',
		emoji: '🇨🇼',
		id: "country:CW",
		name: 'Curaçao',
		price_pro: '9.73',
		price_std: '7.30',
		unicode: 'U+1F1E8 U+1F1FC'
	},
	{
		code: 'CX',
		currency_code: 'AUD',
		currency_name: 'Australia Dollar',
		currency_rate: 0.08186056,
		currency_symbol: '$',
		emoji: '🇨🇽',
		id: "country:CX",
		name: 'Christmas Island',
		price_pro: '8.19',
		price_std: '6.14',
		unicode: 'U+1F1E8 U+1F1FD'
	},
	{
		code: 'CY',
		currency_code: 'EUR',
		currency_name: 'Euro Member Countries',
		currency_rate: 0.050034445,
		currency_symbol: '€',
		emoji: '🇨🇾',
		id: "country:CY",
		name: 'Cyprus',
		price_pro: '5.00',
		price_std: '3.75',
		unicode: 'U+1F1E8 U+1F1FE'
	},
	{
		code: 'CZ',
		currency_code: 'CZK',
		currency_name: 'Czech Republic Koruna',
		currency_rate: 1.23291146,
		currency_symbol: 'Kč',
		emoji: '🇨🇿',
		id: "country:CZ",
		name: 'Czechia',
		price_pro: '123.29',
		price_std: '92.47',
		unicode: 'U+1F1E8 U+1F1FF'
	},
	{
		code: 'DE',
		currency_code: 'EUR',
		currency_name: 'Euro Member Countries',
		currency_rate: 0.050034445,
		currency_symbol: '€',
		emoji: '🇩🇪',
		id: "country:DE",
		name: 'Germany',
		price_pro: '5.00',
		price_std: '3.75',
		unicode: 'U+1F1E9 U+1F1EA'
	},
	{
		code: 'DG',
		currency_code: '?',
		currency_name: '?',
		currency_rate: 1,
		currency_symbol: '?',
		emoji: '🇩🇬',
		id: "country:DG",
		name: 'Diego Garcia',
		price_pro: '100.00',
		price_std: '75.00',
		unicode: 'U+1F1E9 U+1F1EC'
	},
	{
		code: 'DJ',
		currency_code: 'DJF',
		currency_name: 'Djiboutian franc',
		currency_rate: 9.65373148,
		currency_symbol: 'Fdj',
		emoji: '🇩🇯',
		id: "country:DJ",
		name: 'Djibouti',
		price_pro: '965.37',
		price_std: '724.03',
		unicode: 'U+1F1E9 U+1F1EF'
	},
	{
		code: 'DK',
		currency_code: 'DKK',
		currency_name: 'Denmark Krone',
		currency_rate: 0.37327654,
		currency_symbol: 'kr',
		emoji: '🇩🇰',
		id: "country:DK",
		name: 'Denmark',
		price_pro: '37.33',
		price_std: '28.00',
		unicode: 'U+1F1E9 U+1F1F0'
	},
	{
		code: 'DM',
		currency_code: 'XCD',
		currency_name: 'East Caribbean Dollar',
		currency_rate: 0.14666974,
		currency_symbol: '$',
		emoji: '🇩🇲',
		id: "country:DM",
		name: 'Dominica',
		price_pro: '14.67',
		price_std: '11.00',
		unicode: 'U+1F1E9 U+1F1F2'
	},
	{
		code: 'DO',
		currency_code: 'DOP',
		currency_name: 'Dominican Republic Peso',
		currency_rate: 3.19357604,
		currency_symbol: 'RD$',
		emoji: '🇩🇴',
		id: "country:DO",
		name: 'Dominican Republic',
		price_pro: '319.36',
		price_std: '239.52',
		unicode: 'U+1F1E9 U+1F1F4'
	},
	{
		code: 'DZ',
		currency_code: 'DZD',
		currency_name: 'Algerian dinar',
		currency_rate: 7.30474716,
		currency_symbol: 'دج',
		emoji: '🇩🇿',
		id: "country:DZ",
		name: 'Algeria',
		price_pro: '731.47',
		price_std: '547.86',
		unicode: 'U+1F1E9 U+1F1FF'
	},
	{
		code: 'EA',
		currency_code: '?',
		currency_name: '?',
		currency_rate: 1,
		currency_symbol: '?',
		emoji: '🇪🇦',
		id: "country:EA",
		name: 'Ceuta & Melilla',
		price_pro: '100.00',
		price_std: '75.00',
		unicode: 'U+1F1EA U+1F1E6'
	},
	{
		code: 'EC',
		currency_code: 'USD',
		currency_name: 'United States Dollar',
		currency_rate: 0.054288271,
		currency_symbol: '$',
		emoji: '🇪🇨',
		id: "country:EC",
		name: 'Ecuador',
		price_pro: '5.43',
		price_std: '4.07',
		unicode: 'U+1F1EA U+1F1E8'
	},
	{
		code: 'EE',
		currency_code: 'EUR',
		currency_name: 'Euro Member Countries',
		currency_rate: 0.050034445,
		currency_symbol: '€',
		emoji: '🇪🇪',
		id: "country:EE",
		name: 'Estonia',
		price_pro: '5.00',
		price_std: '3.75',
		unicode: 'U+1F1EA U+1F1EA'
	},
	{
		code: 'EG',
		currency_code: 'EGP',
		currency_name: 'Egypt Pound',
		currency_rate: 2.55835136,
		currency_symbol: '£',
		emoji: '🇪🇬',
		id: "country:EG",
		name: 'Egypt',
		price_pro: '255.84',
		price_std: '191.88',
		unicode: 'U+1F1EA U+1F1EC'
	},
	{
		code: 'EH',
		currency_code: 'MAD',
		currency_name: 'Moroccan Dirham',
		currency_rate: 0.54042448,
		currency_symbol: 'DH',
		emoji: '🇪🇭',
		id: "country:EH",
		name: 'Western Sahara',
		price_pro: '54.04',
		price_std: '40.53',
		unicode: 'U+1F1EA U+1F1ED'
	},
	{
		code: 'ER',
		currency_code: 'ERN',
		currency_name: 'Eritrean nakfa',
		currency_rate: 0.81432406,
		currency_symbol: 'Nkf',
		emoji: '🇪🇷',
		id: "country:ER",
		name: 'Eritrea',
		price_pro: '81.43',
		price_std: '61.07',
		unicode: 'U+1F1EA U+1F1F7'
	},
	{
		code: 'ES',
		currency_code: 'EUR',
		currency_name: 'Euro Member Countries',
		currency_rate: 0.050034445,
		currency_symbol: '€',
		emoji: '🇪🇸',
		id: "country:ES",
		name: 'Spain',
		price_pro: '5.00',
		price_std: '3.75',
		unicode: 'U+1F1EA U+1F1F8'
	},
	{
		code: 'ET',
		currency_code: 'ETB',
		currency_name: 'Ethiopian birr',
		currency_rate: 3.11648424,
		currency_symbol: 'ብር',
		emoji: '🇪🇹',
		id: "country:ET",
		name: 'Ethiopia',
		price_pro: '311.65',
		price_std: '233.74',
		unicode: 'U+1F1EA U+1F1F9'
	},
	{
		code: 'EU',
		currency_code: '?',
		currency_name: '?',
		currency_rate: 1,
		currency_symbol: '?',
		emoji: '🇪🇺',
		id: "country:EU",
		name: 'European Union',
		price_pro: '100.00',
		price_std: '75.00',
		unicode: 'U+1F1EA U+1F1FA'
	},
	{
		code: 'FI',
		currency_code: 'EUR',
		currency_name: 'Euro Member Countries',
		currency_rate: 0.050034445,
		currency_symbol: '€',
		emoji: '🇫🇮',
		id: "country:FI",
		name: 'Finland',
		price_pro: '5.00',
		price_std: '3.75',
		unicode: 'U+1F1EB U+1F1EE'
	},
	{
		code: 'FJ',
		currency_code: 'FJD',
		currency_name: 'Fiji Dollar',
		currency_rate: 0.12290676,
		currency_symbol: '$',
		emoji: '🇫🇯',
		id: "country:FJ",
		name: 'Fiji',
		price_pro: '12.29',
		price_std: '9.22',
		unicode: 'U+1F1EB U+1F1EF'
	},
	{
		code: 'FK',
		currency_code: 'FKP',
		currency_name: 'Falkland Islands (Malvinas) Pound',
		currency_rate: 0.042610495,
		currency_symbol: '€',
		emoji: '🇫🇰',
		id: "country:FK",
		name: 'Falkland Islands',
		price_pro: '4.26',
		price_std: '3.20',
		unicode: 'U+1F1EB U+1F1F0'
	},
	{
		code: 'FM',
		currency_code: 'USD',
		currency_name: 'United States Dollar',
		currency_rate: 0.054288271,
		currency_symbol: '$',
		emoji: '🇫🇲',
		id: "country:FM",
		name: 'Micronesia',
		price_pro: '5.43',
		price_std: '4.07',
		unicode: 'U+1F1EB U+1F1F2'
	},
	{
		code: 'FO',
		currency_code: 'DKK',
		currency_name: 'Denmark Krone',
		currency_rate: 0.37327654,
		currency_symbol: 'kr',
		emoji: '🇫🇴',
		id: "country:FO",
		name: 'Faroe Islands',
		price_pro: '37.33',
		price_std: '28.00',
		unicode: 'U+1F1EB U+1F1F4'
	},
	{
		code: 'FR',
		currency_code: 'EUR',
		currency_name: 'Euro Member Countries',
		currency_rate: 0.050034445,
		currency_symbol: '€',
		emoji: '🇫🇷',
		id: "country:FR",
		name: 'France',
		price_pro: '5.00',
		price_std: '3.75',
		unicode: 'U+1F1EB U+1F1F7'
	},
	{
		code: 'GA',
		currency_code: '',
		currency_name: '',
		currency_rate: 1,
		currency_symbol: '',
		emoji: '🇬🇦',
		id: "country:GA",
		name: 'Gabon',
		price_pro: '100.00',
		price_std: '75.00',
		unicode: 'U+1F1EC U+1F1E6'
	},
	{
		code: 'GB',
		currency_code: 'GBP',
		currency_name: 'United Kingdom Pound',
		currency_rate: 0.042610495,
		currency_symbol: '£',
		emoji: '🇬🇧',
		id: "country:GB",
		name: 'United Kingdom',
		price_pro: '4.26',
		price_std: '3.50',
		unicode: 'U+1F1EC U+1F1E7'
	},
	{
		code: 'GD',
		currency_code: 'XCD',
		currency_name: 'East Caribbean Dollar',
		currency_rate: 0.14666974,
		currency_symbol: '$',
		emoji: '🇬🇩',
		id: "country:GD",
		name: 'Grenada',
		price_pro: '14.67',
		price_std: '11.00',
		unicode: 'U+1F1EC U+1F1E9'
	},
	{
		code: 'GE',
		currency_code: '',
		currency_name: '',
		currency_rate: 1,
		currency_symbol: '',
		emoji: '🇬🇪',
		id: "country:GE",
		name: 'Georgia',
		price_pro: '100.00',
		price_std: '75.00',
		unicode: 'U+1F1EC U+1F1EA'
	},
	{
		code: 'GF',
		currency_code: 'EUR',
		currency_name: 'Euro Member Countries',
		currency_rate: 0.050034445,
		currency_symbol: '€',
		emoji: '🇬🇫',
		id: "country:GF",
		name: 'French Guiana',
		price_pro: '5.00',
		price_std: '3.75',
		unicode: 'U+1F1EC U+1F1EB'
	},
	{
		code: 'GG',
		currency_code: 'GBP',
		currency_name: 'United Kingdom Pound',
		currency_rate: 0.042610495,
		currency_symbol: '£',
		emoji: '🇬🇬',
		id: "country:GG",
		name: 'Guernsey',
		price_pro: '4.26',
		price_std: '3.20',
		unicode: 'U+1F1EC U+1F1EC'
	},
	{
		code: 'GH',
		currency_code: 'GHS',
		currency_name: 'Ghana Cedi',
		currency_rate: 0.78919844,
		currency_symbol: '¢',
		emoji: '🇬🇭',
		id: "country:GH",
		name: 'Ghana',
		price_pro: '78.92',
		price_std: '59.19',
		unicode: 'U+1F1EC U+1F1ED'
	},
	{
		code: 'GI',
		currency_code: 'GIP',
		currency_name: 'Gibraltar Pound',
		currency_rate: 0.042610495,
		currency_symbol: '£',
		emoji: '🇬🇮',
		id: "country:GI",
		name: 'Gibraltar',
		price_pro: '4.26',
		price_std: '3.20',
		unicode: 'U+1F1EC U+1F1EE'
	},
	{
		code: 'GL',
		currency_code: 'DKK',
		currency_name: 'Denmark Krone',
		currency_rate: 0.37327654,
		currency_symbol: 'kr',
		emoji: '🇬🇱',
		id: "country:GL",
		name: 'Greenland',
		price_pro: '37.33',
		price_std: '28.00',
		unicode: 'U+1F1EC U+1F1F1'
	},
	{
		code: 'GM',
		currency_code: '',
		currency_name: '',
		currency_rate: 1,
		currency_symbol: '',
		emoji: '🇬🇲',
		id: "country:GM",
		name: 'Gambia',
		price_pro: '100.00',
		price_std: '75.00',
		unicode: 'U+1F1EC U+1F1F2'
	},
	{
		code: 'GN',
		currency_code: '',
		currency_name: '',
		currency_rate: 1,
		currency_symbol: '',
		emoji: '🇬🇳',
		id: "country:GN",
		name: 'Guinea',
		price_pro: '100.00',
		price_std: '75.00',
		unicode: 'U+1F1EC U+1F1F3'
	},
	{
		code: 'GP',
		currency_code: 'EUR',
		currency_name: 'Euro Member Countries',
		currency_rate: 0.050034445,
		currency_symbol: '€',
		emoji: '🇬🇵',
		id: "country:GP",
		name: 'Guadeloupe',
		price_pro: '5.00',
		price_std: '3.75',
		unicode: 'U+1F1EC U+1F1F5'
	},
	{
		code: 'GQ',
		currency_code: '',
		currency_name: '',
		currency_rate: 1,
		currency_symbol: '',
		emoji: '🇬🇶',
		id: "country:GQ",
		name: 'Equatorial Guinea',
		price_pro: '100.00',
		price_std: '75.00',
		unicode: 'U+1F1EC U+1F1F6'
	},
	{
		code: 'GR',
		currency_code: 'EUR',
		currency_name: 'Euro Member Countries',
		currency_rate: 0.050034445,
		currency_symbol: '€',
		emoji: '🇬🇷',
		id: "country:GR",
		name: 'Greece',
		price_pro: '5.00',
		price_std: '3.75',
		unicode: 'U+1F1EC U+1F1F7'
	},
	{
		code: 'GS',
		currency_code: 'GBP',
		currency_name: 'United Kingdom Pound',
		currency_rate: 0.042610495,
		currency_symbol: '£',
		emoji: '🇬🇸',
		id: "country:GS",
		name: 'South Georgia & South Sandwich Islands',
		price_pro: '4.26',
		price_std: '3.20',
		unicode: 'U+1F1EC U+1F1F8'
	},
	{
		code: 'GT',
		currency_code: 'GTQ',
		currency_name: 'Guatemala Quetzal',
		currency_rate: 0.42116349,
		currency_symbol: 'Q',
		emoji: '🇬🇹',
		id: "country:GT",
		name: 'Guatemala',
		price_pro: '42.12',
		price_std: '31.59',
		unicode: 'U+1F1EC U+1F1F9'
	},
	{
		code: 'GU',
		currency_code: 'USD',
		currency_name: 'United States Dollar',
		currency_rate: 0.054288271,
		currency_symbol: '$',
		emoji: '🇬🇺',
		id: "country:GU",
		name: 'Guam',
		price_pro: '5.43',
		price_std: '4.07',
		unicode: 'U+1F1EC U+1F1FA'
	},
	{
		code: 'GW',
		currency_code: 'XOF',
		currency_name: 'West African CFA franc',
		currency_rate: 32.8204447,
		currency_symbol: 'F.CFA',
		emoji: '🇬🇼',
		id: "country:GW",
		name: 'Guinea-Bissau',
		price_pro: '3282.04',
		price_std: '2461.53',
		unicode: 'U+1F1EC U+1F1FC'
	},
	{
		code: 'GY',
		currency_code: 'GYD',
		currency_name: 'Guyana Dollar',
		currency_rate: 11.32515109,
		currency_symbol: '$',
		emoji: '🇬🇾',
		id: "country:GY",
		name: 'Guyana',
		price_pro: '1132.52',
		price_std: '849.39',
		unicode: 'U+1F1EC U+1F1FE'
	},
	{
		code: 'HK',
		currency_code: 'HKD',
		currency_name: 'Hong Kong Dollar',
		currency_rate: 0.42419383,
		currency_symbol: '$',
		emoji: '🇭🇰',
		id: "country:HK",
		name: 'Hong Kong SAR China',
		price_pro: '42.42',
		price_std: '31.81',
		unicode: 'U+1F1ED U+1F1F0'
	},
	{
		code: 'HM',
		currency_code: 'AUD',
		currency_name: 'Australia Dollar',
		currency_rate: 0.08186056,
		currency_symbol: '$',
		emoji: '🇭🇲',
		id: "country:HM",
		name: 'Heard & McDonald Islands',
		price_pro: '8.19',
		price_std: '6.14',
		unicode: 'U+1F1ED U+1F1F2'
	},
	{
		code: 'HN',
		currency_code: 'HNL',
		currency_name: 'Honduras Lempira',
		currency_rate: 1.33975547,
		currency_symbol: 'L',
		emoji: '🇭🇳',
		id: "country:HN",
		name: 'Honduras',
		price_pro: '133.98',
		price_std: '100.48',
		unicode: 'U+1F1ED U+1F1F3'
	},
	{
		code: 'HR',
		currency_code: 'EUR',
		currency_name: 'Euro Member Countries',
		currency_rate: 0.050034445,
		currency_symbol: '€',
		emoji: '🇭🇷',
		id: "country:HR",
		name: 'Croatia',
		price_pro: '5.00',
		price_std: '3.75',
		unicode: 'U+1F1ED U+1F1F7'
	},
	{
		code: 'HT',
		currency_code: '',
		currency_name: '',
		currency_rate: 1,
		currency_symbol: '',
		emoji: '🇭🇹',
		id: "country:HT",
		name: 'Haiti',
		price_pro: '100.00',
		price_std: '75.00',
		unicode: 'U+1F1ED U+1F1F9'
	},
	{
		code: 'HU',
		currency_code: 'HUF',
		currency_name: 'Hungary Forint',
		currency_rate: 19.21655361,
		currency_symbol: 'Ft',
		emoji: '🇭🇺',
		id: "country:HU",
		name: 'Hungary',
		price_pro: '1921.66',
		price_std: '1441.24',
		unicode: 'U+1F1ED U+1F1FA'
	},
	{
		code: 'IC',
		currency_code: '?',
		currency_name: '?',
		currency_rate: 1,
		currency_symbol: '?',
		emoji: '🇮🇨',
		id: "country:IC",
		name: 'Canary Islands',
		price_pro: '100.00',
		price_std: '75.00',
		unicode: 'U+1F1EE U+1F1E8'
	},
	{
		code: 'ID',
		currency_code: 'IDR',
		currency_name: 'Indonesia Rupiah',
		currency_rate: 870.47721843,
		currency_symbol: 'Rp',
		emoji: '🇮🇩',
		id: "country:ID",
		name: 'Indonesia',
		price_pro: '87047.72',
		price_std: '65285.79',
		unicode: 'U+1F1EE U+1F1E9'
	},
	{
		code: 'IE',
		currency_code: 'EUR',
		currency_name: 'Euro Member Countries',
		currency_rate: 0.050034445,
		currency_symbol: '€',
		emoji: '🇮🇪',
		id: "country:IE",
		name: 'Ireland',
		price_pro: '5.00',
		price_std: '3.75',
		unicode: 'U+1F1EE U+1F1EA'
	},
	{
		code: 'IL',
		currency_code: 'ILS',
		currency_name: 'Israel Shekel',
		currency_rate: 0.1988348,
		currency_symbol: '₪',
		emoji: '🇮🇱',
		id: "country:IL",
		name: 'Israel',
		price_pro: '19.88',
		price_std: '14.91',
		unicode: 'U+1F1EE U+1F1F1'
	},
	{
		code: 'IM',
		currency_code: 'GBP',
		currency_name: 'United Kingdom Pound',
		currency_rate: 0.042610495,
		currency_symbol: '£',
		emoji: '🇮🇲',
		id: "country:IM",
		name: 'Isle of Man',
		price_pro: '4.26',
		price_std: '3.20',
		unicode: 'U+1F1EE U+1F1F2'
	},
	{
		code: 'IN',
		currency_code: 'INR',
		currency_name: 'India Rupee',
		currency_rate: 4.50994852,
		currency_symbol: '₹',
		emoji: '🇮🇳',
		id: "country:IN",
		name: 'India',
		price_pro: '450.99',
		price_std: '338.25',
		unicode: 'U+1F1EE U+1F1F3'
	},
	{
		code: 'IO',
		currency_code: 'USD',
		currency_name: 'United States Dollar',
		currency_rate: 0.054288271,
		currency_symbol: '$',
		emoji: '🇮🇴',
		id: "country:IO",
		name: 'British Indian Ocean Territory',
		price_pro: '5.43',
		price_std: '4.07',
		unicode: 'U+1F1EE U+1F1F4'
	},
	{
		code: 'IQ',
		currency_code: '',
		currency_name: '',
		currency_rate: 1,
		currency_symbol: '',
		emoji: '🇮🇶',
		id: "country:IQ",
		name: 'Iraq',
		price_pro: '100.00',
		price_std: '75.00',
		unicode: 'U+1F1EE U+1F1F6'
	},
	{
		code: 'IR',
		currency_code: 'IRR',
		currency_name: 'Iran Rial',
		currency_rate: 2274.47758763,
		currency_symbol: '﷼',
		emoji: '🇮🇷',
		id: "country:IR",
		name: 'Iran',
		price_pro: '227447.76',
		price_std: '170585.82',
		unicode: 'U+1F1EE U+1F1F7'
	},
	{
		code: 'IS',
		currency_code: 'ISK',
		currency_name: 'Iceland Krona',
		currency_rate: 7.50035847,
		currency_symbol: 'kr',
		emoji: '🇮🇸',
		id: "country:IS",
		name: 'Iceland',
		price_pro: '750.04',
		price_std: '562.53',
		unicode: 'U+1F1EE U+1F1F8'
	},
	{
		code: 'IT',
		currency_code: 'EUR',
		currency_name: 'Euro Member Countries',
		currency_rate: 0.050034445,
		currency_symbol: '€',
		emoji: '🇮🇹',
		id: "country:IT",
		name: 'Italy',
		price_pro: '5.00',
		price_std: '3.75',
		unicode: 'U+1F1EE U+1F1F9'
	},
	{
		code: 'JE',
		currency_code: 'GBP',
		currency_name: 'United Kingdom Pound',
		currency_rate: 0.042610495,
		currency_symbol: '£',
		emoji: '🇯🇪',
		id: "country:JE",
		name: 'Jersey',
		price_pro: '4.26',
		price_std: '3.20',
		unicode: 'U+1F1EF U+1F1EA'
	},
	{
		code: 'JM',
		currency_code: 'JMD',
		currency_name: 'Jamaica Dollar',
		currency_rate: 8.48407091,
		currency_symbol: 'J$',
		emoji: '🇯🇲',
		id: "country:JM",
		name: 'Jamaica',
		price_pro: '848.41',
		price_std: '636.31',
		unicode: 'U+1F1EF U+1F1F2'
	},
	{
		code: 'JO',
		currency_code: '',
		currency_name: '',
		currency_rate: 1,
		currency_symbol: '',
		emoji: '🇯🇴',
		id: "country:JO",
		name: 'Jordan',
		price_pro: '100.00',
		price_std: '75.00',
		unicode: 'U+1F1EF U+1F1F4'
	},
	{
		code: 'JP',
		currency_code: 'JPY',
		currency_name: 'Japan Yen',
		currency_rate: 8.50813272,
		currency_symbol: '¥',
		emoji: '🇯🇵',
		id: "country:JP",
		name: 'Japan',
		price_pro: '850.81',
		price_std: '638.11',
		unicode: 'U+1F1EF U+1F1F5'
	},
	{
		code: 'KE',
		currency_code: '',
		currency_name: '',
		currency_rate: 1,
		currency_symbol: '',
		emoji: '🇰🇪',
		id: "country:KE",
		name: 'Kenya',
		price_pro: '100.00',
		price_std: '75.00',
		unicode: 'U+1F1F0 U+1F1EA'
	},
	{
		code: 'KG',
		currency_code: 'KGS',
		currency_name: 'Kyrgyzstan Som',
		currency_rate: 4.77495928,
		currency_symbol: 'лв',
		emoji: '🇰🇬',
		id: "country:KG",
		name: 'Kyrgyzstan',
		price_pro: '477.50',
		price_std: '358.12',
		unicode: 'U+1F1F0 U+1F1EC'
	},
	{
		code: 'KH',
		currency_code: 'KHR',
		currency_name: 'Cambodia Riel',
		currency_rate: 221.09994956,
		currency_symbol: '៛',
		emoji: '🇰🇭',
		id: "country:KH",
		name: 'Cambodia',
		price_pro: '22109.99',
		price_std: '16582.50',
		unicode: 'U+1F1F0 U+1F1ED'
	},
	{
		code: 'KI',
		currency_code: 'AUD',
		currency_name: 'Australia Dollar',
		currency_rate: 0.08186056,
		currency_symbol: '$',
		emoji: '🇰🇮',
		id: "country:KI",
		name: 'Kiribati',
		price_pro: '8.19',
		price_std: '6.14',
		unicode: 'U+1F1F0 U+1F1EE'
	},
	{
		code: 'KM',
		currency_code: '',
		currency_name: '',
		currency_rate: 1,
		currency_symbol: '',
		emoji: '🇰🇲',
		id: "country:KM",
		name: 'Comoros',
		price_pro: '100.00',
		price_std: '75.00',
		unicode: 'U+1F1F0 U+1F1F2'
	},
	{
		code: 'KN',
		currency_code: 'XCD',
		currency_name: 'East Caribbean Dollar',
		currency_rate: 0.14666974,
		currency_symbol: '$',
		emoji: '🇰🇳',
		id: "country:KN",
		name: 'St. Kitts & Nevis',
		price_pro: '14.67',
		price_std: '11.00',
		unicode: 'U+1F1F0 U+1F1F3'
	},
	{
		code: 'KP',
		currency_code: 'KPW',
		currency_name: 'Korea (North) Won',
		currency_rate: 48.85938119,
		currency_symbol: '₩',
		emoji: '🇰🇵',
		id: "country:KP",
		name: 'North Korea',
		price_pro: '4885.94',
		price_std: '3664.45',
		unicode: 'U+1F1F0 U+1F1F5'
	},
	{
		code: 'KR',
		currency_code: 'KRW',
		currency_name: 'Korea (South) Won',
		currency_rate: 74.07977699,
		currency_symbol: '₩',
		emoji: '🇰🇷',
		id: "country:KR",
		name: 'South Korea',
		price_pro: '7407.98',
		price_std: '5555.98',
		unicode: 'U+1F1F0 U+1F1F7'
	},
	{
		code: 'KW',
		currency_code: '',
		currency_name: '',
		currency_rate: 1,
		currency_symbol: '',
		emoji: '🇰🇼',
		id: "country:KW",
		name: 'Kuwait',
		price_pro: '100.00',
		price_std: '75.00',
		unicode: 'U+1F1F0 U+1F1FC'
	},
	{
		code: 'KY',
		currency_code: 'KYD',
		currency_name: 'Cayman Islands Dollar',
		currency_rate: 0.044607885,
		currency_symbol: '$',
		emoji: '🇰🇾',
		id: "country:KY",
		name: 'Cayman Islands',
		price_pro: '4.46',
		price_std: '3.35',
		unicode: 'U+1F1F0 U+1F1FE'
	},
	{
		code: 'KZ',
		currency_code: 'KZT',
		currency_name: 'Kazakhstan Tenge',
		currency_rate: 24.02807185,
		currency_symbol: 'лв',
		emoji: '🇰🇿',
		id: "country:KZ",
		name: 'Kazakhstan',
		price_pro: '2402.81',
		price_std: '1802.11',
		unicode: 'U+1F1F0 U+1F1FF'
	},
	{
		code: 'LA',
		currency_code: 'LAK',
		currency_name: 'Laos Kip',
		currency_rate: 1166.79890811,
		currency_symbol: '₭',
		emoji: '🇱🇦',
		id: "country:LA",
		name: 'Laos',
		price_pro: '116679.89',
		price_std: '87509.92',
		unicode: 'U+1F1F1 U+1F1E6'
	},
	{
		code: 'LB',
		currency_code: 'LBP',
		currency_name: 'Lebanon Pound',
		currency_rate: 4967.76167884,
		currency_symbol: '£',
		emoji: '🇱🇧',
		id: "country:LB",
		name: 'Lebanon',
		price_pro: '496776.17',
		price_std: '372582.13',
		unicode: 'U+1F1F1 U+1F1E7'
	},
	{
		code: 'LC',
		currency_code: 'XCD',
		currency_name: 'East Caribbean Dollar',
		currency_rate: 0.14666974,
		currency_symbol: '$',
		emoji: '🇱🇨',
		id: "country:LC",
		name: 'St. Lucia',
		price_pro: '14.67',
		price_std: '11.00',
		unicode: 'U+1F1F1 U+1F1E8'
	},
	{
		code: 'LI',
		currency_code: 'CHF',
		currency_name: 'Switzerland Franc',
		currency_rate: 0.049641764,
		currency_symbol: 'CHF',
		emoji: '🇱🇮',
		id: "country:LI",
		name: 'Liechtenstein',
		price_pro: '4.96',
		price_std: '3.72',
		unicode: 'U+1F1F1 U+1F1EE'
	},
	{
		code: 'LK',
		currency_code: 'LKR',
		currency_name: 'Sri Lanka Rupee',
		currency_rate: 16.25089051,
		currency_symbol: '₨',
		emoji: '🇱🇰',
		id: "country:LK",
		name: 'Sri Lanka',
		price_pro: '1625.09',
		price_std: '1218.82',
		unicode: 'U+1F1F1 U+1F1F0'
	},
	{
		code: 'LR',
		currency_code: 'LRD',
		currency_name: 'Liberia Dollar',
		currency_rate: 10.50744029,
		currency_symbol: '$',
		emoji: '🇱🇷',
		id: "country:LR",
		name: 'Liberia',
		price_pro: '1050.74',
		price_std: '788.06',
		unicode: 'U+1F1F1 U+1F1F7'
	},
	{
		code: 'LS',
		currency_code: '',
		currency_name: '',
		currency_rate: 1,
		currency_symbol: '',
		emoji: '🇱🇸',
		id: "country:LS",
		name: 'Lesotho',
		price_pro: '100.00',
		price_std: '75.00',
		unicode: 'U+1F1F1 U+1F1F8'
	},
	{
		code: 'LT',
		currency_code: 'EUR',
		currency_name: 'Euro Member Countries',
		currency_rate: 0.050034445,
		currency_symbol: '€',
		emoji: '🇱🇹',
		id: "country:LT",
		name: 'Lithuania',
		price_pro: '5.00',
		price_std: '3.75',
		unicode: 'U+1F1F1 U+1F1F9'
	},
	{
		code: 'LU',
		currency_code: 'EUR',
		currency_name: 'Euro Member Countries',
		currency_rate: 0.050034445,
		currency_symbol: '€',
		emoji: '🇱🇺',
		id: "country:LU",
		name: 'Luxembourg',
		price_pro: '5.00',
		price_std: '3.75',
		unicode: 'U+1F1F1 U+1F1FA'
	},
	{
		code: 'LV',
		currency_code: 'EUR',
		currency_name: 'Euro Member Countries',
		currency_rate: 0.050034445,
		currency_symbol: '€',
		emoji: '🇱🇻',
		id: "country:LV",
		name: 'Latvia',
		price_pro: '5.00',
		price_std: '3.75',
		unicode: 'U+1F1F1 U+1F1FB'
	},
	{
		code: 'LY',
		currency_code: '',
		currency_name: '',
		currency_rate: 1,
		currency_symbol: '',
		emoji: '🇱🇾',
		id: "country:LY",
		name: 'Libya',
		price_pro: '100.00',
		price_std: '75.00',
		unicode: 'U+1F1F1 U+1F1FE'
	},
	{
		code: 'MA',
		currency_code: 'MAD',
		currency_name: 'Moroccan Dirham',
		currency_rate: 0.54042448,
		currency_symbol: 'DH',
		emoji: '🇲🇦',
		id: "country:MA",
		name: 'Morocco',
		price_pro: '54.04',
		price_std: '40.53',
		unicode: 'U+1F1F2 U+1F1E6'
	},
	{
		code: 'MC',
		currency_code: 'EUR',
		currency_name: 'Euro Member Countries',
		currency_rate: 0.050034445,
		currency_symbol: '€',
		emoji: '🇲🇨',
		id: "country:MC",
		name: 'Monaco',
		price_pro: '5.00',
		price_std: '3.75',
		unicode: 'U+1F1F2 U+1F1E8'
	},
	{
		code: 'MD',
		currency_code: '',
		currency_name: '',
		currency_rate: 1,
		currency_symbol: '',
		emoji: '🇲🇩',
		id: "country:MD",
		name: 'Moldova',
		price_pro: '100.00',
		price_std: '75.00',
		unicode: 'U+1F1F2 U+1F1E9'
	},
	{
		code: 'ME',
		currency_code: 'EUR',
		currency_name: 'Euro Member Countries',
		currency_rate: 0.050034445,
		currency_symbol: '€',
		emoji: '🇲🇪',
		id: "country:ME",
		name: 'Montenegro',
		price_pro: '5.00',
		price_std: '3.75',
		unicode: 'U+1F1F2 U+1F1EA'
	},
	{
		code: 'MF',
		currency_code: 'EUR',
		currency_name: 'Euro Member Countries',
		currency_rate: 0.050034445,
		currency_symbol: '€',
		emoji: '🇲🇫',
		id: "country:MF",
		name: 'St. Martin',
		price_pro: '5.00',
		price_std: '3.75',
		unicode: 'U+1F1F2 U+1F1EB'
	},
	{
		code: 'MG',
		currency_code: '',
		currency_name: '',
		currency_rate: 1,
		currency_symbol: '',
		emoji: '🇲🇬',
		id: "country:MG",
		name: 'Madagascar',
		price_pro: '100.00',
		price_std: '75.00',
		unicode: 'U+1F1F2 U+1F1EC'
	},
	{
		code: 'MH',
		currency_code: 'USD',
		currency_name: 'United States Dollar',
		currency_rate: 0.054288271,
		currency_symbol: '$',
		emoji: '🇲🇭',
		id: "country:MH",
		name: 'Marshall Islands',
		price_pro: '5.43',
		price_std: '4.07',
		unicode: 'U+1F1F2 U+1F1ED'
	},
	{
		code: 'MK',
		currency_code: 'MKD',
		currency_name: 'Macedonia Denar',
		currency_rate: 3.08494146,
		currency_symbol: 'ден',
		emoji: '🇲🇰',
		id: "country:MK",
		name: 'Macedonia',
		price_pro: '308.49',
		price_std: '231.37',
		unicode: 'U+1F1F2 U+1F1F0'
	},
	{
		code: 'ML',
		currency_code: 'XOF',
		currency_name: 'West African CFA franc',
		currency_rate: 32.8204447,
		currency_symbol: 'F.CFA',
		emoji: '🇲🇱',
		id: "country:ML",
		name: 'Mali',
		price_pro: '3282.04',
		price_std: '2461.53',
		unicode: 'U+1F1F2 U+1F1F1'
	},
	{
		code: 'MM',
		currency_code: '',
		currency_name: '',
		currency_rate: 1,
		currency_symbol: '',
		emoji: '🇲🇲',
		id: "country:MM",
		name: 'Myanmar (Burma)',
		price_pro: '100.00',
		price_std: '75.00',
		unicode: 'U+1F1F2 U+1F1F2'
	},
	{
		code: 'MN',
		currency_code: 'MNT',
		currency_name: 'Mongolia Tughrik',
		currency_rate: 184.26774659,
		currency_symbol: '₮',
		emoji: '🇲🇳',
		id: "country:MN",
		name: 'Mongolia',
		price_pro: '18426.77',
		price_std: '13820.08',
		unicode: 'U+1F1F2 U+1F1F3'
	},
	{
		code: 'MO',
		currency_code: '',
		currency_name: '',
		currency_rate: 1,
		currency_symbol: '',
		emoji: '🇲🇴',
		id: "country:MO",
		name: 'Macau SAR China',
		price_pro: '100.00',
		price_std: '75.00',
		unicode: 'U+1F1F2 U+1F1F4'
	},
	{
		code: 'MP',
		currency_code: 'USD',
		currency_name: 'United States Dollar',
		currency_rate: 0.054288271,
		currency_symbol: '$',
		emoji: '🇲🇵',
		id: "country:MP",
		name: 'Northern Mariana Islands',
		price_pro: '5.43',
		price_std: '4.07',
		unicode: 'U+1F1F2 U+1F1F5'
	},
	{
		code: 'MQ',
		currency_code: 'EUR',
		currency_name: 'Euro Member Countries',
		currency_rate: 0.050034445,
		currency_symbol: '€',
		emoji: '🇲🇶',
		id: "country:MQ",
		name: 'Martinique',
		price_pro: '5.00',
		price_std: '3.75',
		unicode: 'U+1F1F2 U+1F1F6'
	},
	{
		code: 'MR',
		currency_code: '',
		currency_name: '',
		currency_rate: 1,
		currency_symbol: '',
		emoji: '🇲🇷',
		id: "country:MR",
		name: 'Mauritania',
		price_pro: '100.00',
		price_std: '75.00',
		unicode: 'U+1F1F2 U+1F1F7'
	},
	{
		code: 'MS',
		currency_code: 'XCD',
		currency_name: 'East Caribbean Dollar',
		currency_rate: 0.14666974,
		currency_symbol: '$',
		emoji: '🇲🇸',
		id: "country:MS",
		name: 'Montserrat',
		price_pro: '14.67',
		price_std: '11.00',
		unicode: 'U+1F1F2 U+1F1F8'
	},
	{
		code: 'MT',
		currency_code: 'EUR',
		currency_name: 'Euro Member Countries',
		currency_rate: 0.050034445,
		currency_symbol: '€',
		emoji: '🇲🇹',
		id: "country:MT",
		name: 'Malta',
		price_pro: '5.00',
		price_std: '3.75',
		unicode: 'U+1F1F2 U+1F1F9'
	},
	{
		code: 'MU',
		currency_code: 'MUR',
		currency_name: 'Mauritius Rupee',
		currency_rate: 2.50254609,
		currency_symbol: '₨',
		emoji: '🇲🇺',
		id: "country:MU",
		name: 'Mauritius',
		price_pro: '250.25',
		price_std: '187.69',
		unicode: 'U+1F1F2 U+1F1FA'
	},
	{
		code: 'MV',
		currency_code: '',
		currency_name: '',
		currency_rate: 1,
		currency_symbol: '',
		emoji: '🇲🇻',
		id: "country:MV",
		name: 'Maldives',
		price_pro: '100.00',
		price_std: '75.00',
		unicode: 'U+1F1F2 U+1F1FB'
	},
	{
		code: 'MW',
		currency_code: '',
		currency_name: '',
		currency_rate: 1,
		currency_symbol: '',
		emoji: '🇲🇼',
		id: "country:MW",
		name: 'Malawi',
		price_pro: '100.00',
		price_std: '75.00',
		unicode: 'U+1F1F2 U+1F1FC'
	},
	{
		code: 'MX',
		currency_code: 'MXN',
		currency_name: 'Mexico Peso',
		currency_rate: 0.90537509,
		currency_symbol: '$',
		emoji: '🇲🇽',
		id: "country:MX",
		name: 'Mexico',
		price_pro: '90.54',
		price_std: '67.90',
		unicode: 'U+1F1F2 U+1F1FD'
	},
	{
		code: 'MY',
		currency_code: 'MYR',
		currency_name: 'Malaysia Ringgit',
		currency_rate: 0.25571653,
		currency_symbol: 'RM',
		emoji: '🇲🇾',
		id: "country:MY",
		name: 'Malaysia',
		price_pro: '25.57',
		price_std: '19.18',
		unicode: 'U+1F1F2 U+1F1FE'
	},
	{
		code: 'MZ',
		currency_code: 'MZN',
		currency_name: 'Mozambique Metical',
		currency_rate: 3.45158809,
		currency_symbol: 'MT',
		emoji: '🇲🇿',
		id: "country:MZ",
		name: 'Mozambique',
		price_pro: '345.16',
		price_std: '258.87',
		unicode: 'U+1F1F2 U+1F1FF'
	},
	{
		code: 'NA',
		currency_code: 'NAD',
		currency_name: 'Namibia Dollar',
		currency_rate: 1,
		currency_symbol: '$',
		emoji: '🇳🇦',
		id: "country:NA",
		name: 'Namibia',
		price_pro: '100.00',
		price_std: '75.00',
		unicode: 'U+1F1F3 U+1F1E6'
	},
	{
		code: 'NC',
		currency_code: '',
		currency_name: '',
		currency_rate: 1,
		currency_symbol: '',
		emoji: '🇳🇨',
		id: "country:NC",
		name: 'New Caledonia',
		price_pro: '100.00',
		price_std: '75.00',
		unicode: 'U+1F1F3 U+1F1E8'
	},
	{
		code: 'NE',
		currency_code: 'XOF',
		currency_name: 'West African CFA franc',
		currency_rate: 32.8204447,
		currency_symbol: 'F.CFA',
		emoji: '🇳🇪',
		id: "country:NE",
		name: 'Niger',
		price_pro: '3282.04',
		price_std: '2461.53',
		unicode: 'U+1F1F3 U+1F1EA'
	},
	{
		code: 'NF',
		currency_code: 'AUD',
		currency_name: 'Australia Dollar',
		currency_rate: 0.08186056,
		currency_symbol: '$',
		emoji: '🇳🇫',
		id: "country:NF",
		name: 'Norfolk Island',
		price_pro: '8.19',
		price_std: '6.14',
		unicode: 'U+1F1F3 U+1F1EB'
	},
	{
		code: 'NG',
		currency_code: 'NGN',
		currency_name: 'Nigeria Naira',
		currency_rate: 79.75123309,
		currency_symbol: '₦',
		emoji: '🇳🇬',
		id: "country:NG",
		name: 'Nigeria',
		price_pro: '7975.12',
		price_std: '5981.34',
		unicode: 'U+1F1F3 U+1F1EC'
	},
	{
		code: 'NI',
		currency_code: 'NIO',
		currency_name: 'Nicaragua Cordoba Symbol',
		currency_rate: 1.99586394,
		currency_symbol: 'C$',
		emoji: '🇳🇮',
		id: "country:NI",
		name: 'Nicaragua',
		price_pro: '199.59',
		price_std: '149.69',
		unicode: 'U+1F1F3 U+1F1EE'
	},
	{
		code: 'NL',
		currency_code: 'EUR',
		currency_name: 'Euro Member Countries',
		currency_rate: 0.050034445,
		currency_symbol: '€',
		emoji: '🇳🇱',
		id: "country:NL",
		name: 'Netherlands',
		price_pro: '5.00',
		price_std: '3.75',
		unicode: 'U+1F1F3 U+1F1F1'
	},
	{
		code: 'NO',
		currency_code: 'NOK',
		currency_name: 'Norway Krone',
		currency_rate: 0.57453922,
		currency_symbol: 'kr',
		emoji: '🇳🇴',
		id: "country:NO",
		name: 'Norway',
		price_pro: '57.45',
		price_std: '43.09',
		unicode: 'U+1F1F3 U+1F1F4'
	},
	{
		code: 'NP',
		currency_code: 'NPR',
		currency_name: 'Nepal Rupee',
		currency_rate: 7.2193001,
		currency_symbol: '₨',
		emoji: '🇳🇵',
		id: "country:NP",
		name: 'Nepal',
		price_pro: '721.93',
		price_std: '541.45',
		unicode: 'U+1F1F3 U+1F1F5'
	},
	{
		code: 'NR',
		currency_code: 'AUD',
		currency_name: 'Australia Dollar',
		currency_rate: 0.08186056,
		currency_symbol: '$',
		emoji: '🇳🇷',
		id: "country:NR",
		name: 'Nauru',
		price_pro: '8.19',
		price_std: '6.14',
		unicode: 'U+1F1F3 U+1F1F7'
	},
	{
		code: 'NU',
		currency_code: 'NZD',
		currency_name: 'New Zealand Dollar',
		currency_rate: 0.088598209,
		currency_symbol: '$',
		emoji: '🇳🇺',
		id: "country:NU",
		name: 'Niue',
		price_pro: '8.86',
		price_std: '6.64',
		unicode: 'U+1F1F3 U+1F1FA'
	},
	{
		code: 'NZ',
		currency_code: 'NZD',
		currency_name: 'New Zealand Dollar',
		currency_rate: 0.088598209,
		currency_symbol: '$',
		emoji: '🇳🇿',
		id: "country:NZ",
		name: 'New Zealand',
		price_pro: '8.86',
		price_std: '6.64',
		unicode: 'U+1F1F3 U+1F1FF'
	},
	{
		code: 'OM',
		currency_code: 'OMR',
		currency_name: 'Oman Rial',
		currency_rate: 0.020896332,
		currency_symbol: '﷼',
		emoji: '🇴🇲',
		id: "country:OM",
		name: 'Oman',
		price_pro: '2.09',
		price_std: '1.57',
		unicode: 'U+1F1F4 U+1F1F2'
	},
	{
		code: 'PA',
		currency_code: 'PAB',
		currency_name: 'Panama Balboa',
		currency_rate: 0.054288271,
		currency_symbol: 'B/.',
		emoji: '🇵🇦',
		id: "country:PA",
		name: 'Panama',
		price_pro: '5.43',
		price_std: '4.07',
		unicode: 'U+1F1F5 U+1F1E6'
	},
	{
		code: 'PE',
		currency_code: 'PEN',
		currency_name: 'Peru Sol',
		currency_rate: 0.20320011,
		currency_symbol: 'S/.',
		emoji: '🇵🇪',
		id: "country:PE",
		name: 'Peru',
		price_pro: '20.32',
		price_std: '15.24',
		unicode: 'U+1F1F5 U+1F1EA'
	},
	{
		code: 'PF',
		currency_code: '',
		currency_name: '',
		currency_rate: 1,
		currency_symbol: '',
		emoji: '🇵🇫',
		id: "country:PF",
		name: 'French Polynesia',
		price_pro: '100.00',
		price_std: '75.00',
		unicode: 'U+1F1F5 U+1F1EB'
	},
	{
		code: 'PG',
		currency_code: '',
		currency_name: '',
		currency_rate: 1,
		currency_symbol: '',
		emoji: '🇵🇬',
		id: "country:PG",
		name: 'Papua New Guinea',
		price_pro: '100.00',
		price_std: '75.00',
		unicode: 'U+1F1F5 U+1F1EC'
	},
	{
		code: 'PH',
		currency_code: 'PHP',
		currency_name: 'Philippines Peso',
		currency_rate: 3.15383512,
		currency_symbol: '₱',
		emoji: '🇵🇭',
		id: "country:PH",
		name: 'Philippines',
		price_pro: '315.38',
		price_std: '236.54',
		unicode: 'U+1F1F5 U+1F1ED'
	},
	{
		code: 'PK',
		currency_code: 'PKR',
		currency_name: 'Pakistan Rupee',
		currency_rate: 15.12250113,
		currency_symbol: '₨',
		emoji: '🇵🇰',
		id: "country:PK",
		name: 'Pakistan',
		price_pro: '1512.25',
		price_std: '1134.19',
		unicode: 'U+1F1F5 U+1F1F0'
	},
	{
		code: 'PL',
		currency_code: 'PLN',
		currency_name: 'Poland Zloty',
		currency_rate: 0.2129033,
		currency_symbol: 'zł',
		emoji: '🇵🇱',
		id: "country:PL",
		name: 'Poland',
		price_pro: '21.29',
		price_std: '15.97',
		unicode: 'U+1F1F5 U+1F1F1'
	},
	{
		code: 'PM',
		currency_code: 'EUR',
		currency_name: 'Euro Member Countries',
		currency_rate: 0.050034445,
		currency_symbol: '€',
		emoji: '🇵🇲',
		id: "country:PM",
		name: 'St. Pierre & Miquelon',
		price_pro: '5.00',
		price_std: '3.75',
		unicode: 'U+1F1F5 U+1F1F2'
	},
	{
		code: 'PN',
		currency_code: 'NZD',
		currency_name: 'New Zealand Dollar',
		currency_rate: 0.088598209,
		currency_symbol: '$',
		emoji: '🇵🇳',
		id: "country:PN",
		name: 'Pitcairn Islands',
		price_pro: '8.86',
		price_std: '6.64',
		unicode: 'U+1F1F5 U+1F1F3'
	},
	{
		code: 'PR',
		currency_code: 'USD',
		currency_name: 'United States Dollar',
		currency_rate: 0.054288271,
		currency_symbol: '$',
		emoji: '🇵🇷',
		id: "country:PR",
		name: 'Puerto Rico',
		price_pro: '5.43',
		price_std: '4.07',
		unicode: 'U+1F1F5 U+1F1F7'
	},
	{
		code: 'PS',
		currency_code: 'ILS',
		currency_name: 'Israel Shekel',
		currency_rate: 0.1988348,
		currency_symbol: '₪',
		emoji: '🇵🇸',
		id: "country:PS",
		name: 'Palestinian Territories',
		price_pro: '19.88',
		price_std: '14.91',
		unicode: 'U+1F1F5 U+1F1F8'
	},
	{
		code: 'PT',
		currency_code: 'EUR',
		currency_name: 'Euro Member Countries',
		currency_rate: 0.050034445,
		currency_symbol: '€',
		emoji: '🇵🇹',
		id: "country:PT",
		name: 'Portugal',
		price_pro: '5.00',
		price_std: '3.75',
		unicode: 'U+1F1F5 U+1F1F9'
	},
	{
		code: 'PW',
		currency_code: 'USD',
		currency_name: 'United States Dollar',
		currency_rate: 0.054288271,
		currency_symbol: '$',
		emoji: '🇵🇼',
		id: "country:PW",
		name: 'Palau',
		price_pro: '5.43',
		price_std: '4.07',
		unicode: 'U+1F1F5 U+1F1FC'
	},
	{
		code: 'PY',
		currency_code: 'PYG',
		currency_name: 'Paraguay Guarani',
		currency_rate: 407.51002196,
		currency_symbol: 'Gs',
		emoji: '🇵🇾',
		id: "country:PY",
		name: 'Paraguay',
		price_pro: '40751.00',
		price_std: '30563.25',
		unicode: 'U+1F1F5 U+1F1FE'
	},
	{
		code: 'QA',
		currency_code: 'QAR',
		currency_name: 'Qatar Riyal',
		currency_rate: 0.19760931,
		currency_symbol: '﷼',
		emoji: '🇶🇦',
		id: "country:QA",
		name: 'Qatar',
		price_pro: '19.76',
		price_std: '14.82',
		unicode: 'U+1F1F6 U+1F1E6'
	},
	{
		code: 'RE',
		currency_code: 'EUR',
		currency_name: 'Euro Member Countries',
		currency_rate: 0.050034445,
		currency_symbol: '€',
		emoji: '🇷🇪',
		id: "country:RE",
		name: 'Réunion',
		price_pro: '5.00',
		price_std: '3.75',
		unicode: 'U+1F1F7 U+1F1EA'
	},
	{
		code: 'RO',
		currency_code: 'RON',
		currency_name: 'Romania Leu',
		currency_rate: 0.24897363,
		currency_symbol: 'lei',
		emoji: '🇷🇴',
		id: "country:RO",
		name: 'Romania',
		price_pro: '24.90',
		price_std: '18.67',
		unicode: 'U+1F1F7 U+1F1F4'
	},
	{
		code: 'RS',
		currency_code: 'RSD',
		currency_name: 'Serbia Dinar',
		currency_rate: 5.86193818,
		currency_symbol: 'Дин.',
		emoji: '🇷🇸',
		id: "country:RS",
		name: 'Serbia',
		price_pro: '586.19',
		price_std: '439.65',
		unicode: 'U+1F1F7 U+1F1F8'
	},
	{
		code: 'RU',
		currency_code: 'RUB',
		currency_name: 'Russia Ruble',
		currency_rate: 4.93173097,
		currency_symbol: '₽',
		emoji: '🇷🇺',
		id: "country:RU",
		name: 'Russia',
		price_pro: '493.17',
		price_std: '369.88',
		unicode: 'U+1F1F7 U+1F1FA'
	},
	{
		code: 'RW',
		currency_code: '',
		currency_name: '',
		currency_rate: 1,
		currency_symbol: '',
		emoji: '🇷🇼',
		id: "country:RW",
		name: 'Rwanda',
		price_pro: '100.00',
		price_std: '75.00',
		unicode: 'U+1F1F7 U+1F1FC'
	},
	{
		code: 'SA',
		currency_code: 'SAR',
		currency_name: 'Saudi Arabia Riyal',
		currency_rate: 0.20358102,
		currency_symbol: '﷼',
		emoji: '🇸🇦',
		id: "country:SA",
		name: 'Saudi Arabia',
		price_pro: '20.36',
		price_std: '15.27',
		unicode: 'U+1F1F8 U+1F1E6'
	},
	{
		code: 'SB',
		currency_code: 'SBD',
		currency_name: 'Solomon Islands Dollar',
		currency_rate: 0.45014824,
		currency_symbol: '$',
		emoji: '🇸🇧',
		id: "country:SB",
		name: 'Solomon Islands',
		price_pro: '45.01',
		price_std: '33.76',
		unicode: 'U+1F1F8 U+1F1E7'
	},
	{
		code: 'SC',
		currency_code: 'SCR',
		currency_name: 'Seychelles Rupee',
		currency_rate: 0.74298215,
		currency_symbol: '₨',
		emoji: '🇸🇨',
		id: "country:SC",
		name: 'Seychelles',
		price_pro: '74.30',
		price_std: '55.72',
		unicode: 'U+1F1F8 U+1F1E8'
	},
	{
		code: 'SD',
		currency_code: '',
		currency_name: '',
		currency_rate: 1,
		currency_symbol: '',
		emoji: '🇸🇩',
		id: "country:SD",
		name: 'Sudan',
		price_pro: '100.00',
		price_std: '75.00',
		unicode: 'U+1F1F8 U+1F1E9'
	},
	{
		code: 'SE',
		currency_code: 'SEK',
		currency_name: 'Sweden Krona',
		currency_rate: 0.57864832,
		currency_symbol: 'kr',
		emoji: '🇸🇪',
		id: "country:SE",
		name: 'Sweden',
		price_pro: '57.86',
		price_std: '43.40',
		unicode: 'U+1F1F8 U+1F1EA'
	},
	{
		code: 'SG',
		currency_code: 'SGD',
		currency_name: 'Singapore Dollar',
		currency_rate: 0.073254401,
		currency_symbol: '$',
		emoji: '🇸🇬',
		id: "country:SG",
		name: 'Singapore',
		price_pro: '7.33',
		price_std: '5.49',
		unicode: 'U+1F1F8 U+1F1EC'
	},
	{
		code: 'SH',
		currency_code: 'SHP',
		currency_name: 'Saint Helena Pound',
		currency_rate: 0.042610495,
		currency_symbol: '£',
		emoji: '🇸🇭',
		id: "country:SH",
		name: 'St. Helena',
		price_pro: '4.26',
		price_std: '3.20',
		unicode: 'U+1F1F8 U+1F1ED'
	},
	{
		code: 'SI',
		currency_code: 'EUR',
		currency_name: 'Euro Member Countries',
		currency_rate: 0.050034445,
		currency_symbol: '€',
		emoji: '🇸🇮',
		id: "country:SI",
		name: 'Slovenia',
		price_pro: '5.00',
		price_std: '3.75',
		unicode: 'U+1F1F8 U+1F1EE'
	},
	{
		code: 'SJ',
		currency_code: 'NOK',
		currency_name: 'Norway Krone',
		currency_rate: 0.57453922,
		currency_symbol: 'kr',
		emoji: '🇸🇯',
		id: "country:SJ",
		name: 'Svalbard & Jan Mayen',
		price_pro: '57.45',
		price_std: '43.09',
		unicode: 'U+1F1F8 U+1F1EF'
	},
	{
		code: 'SK',
		currency_code: 'EUR',
		currency_name: 'Euro Member Countries',
		currency_rate: 0.050034445,
		currency_symbol: '€',
		emoji: '🇸🇰',
		id: "country:SK",
		name: 'Slovakia',
		price_pro: '5.00',
		price_std: '3.75',
		unicode: 'U+1F1F8 U+1F1F0'
	},
	{
		code: 'SL',
		currency_code: '',
		currency_name: '',
		currency_rate: 1,
		currency_symbol: '',
		emoji: '🇸🇱',
		id: "country:SL",
		name: 'Sierra Leone',
		price_pro: '100.00',
		price_std: '75.00',
		unicode: 'U+1F1F8 U+1F1F1'
	},
	{
		code: 'SM',
		currency_code: 'EUR',
		currency_name: 'Euro Member Countries',
		currency_rate: 0.050034445,
		currency_symbol: '€',
		emoji: '🇸🇲',
		id: "country:SM",
		name: 'San Marino',
		price_pro: '5.00',
		price_std: '3.75',
		unicode: 'U+1F1F8 U+1F1F2'
	},
	{
		code: 'SN',
		currency_code: 'XOF',
		currency_name: 'West African CFA franc',
		currency_rate: 32.8204447,
		currency_symbol: 'F.CFA',
		emoji: '🇸🇳',
		id: "country:SN",
		name: 'Senegal',
		price_pro: '3282.04',
		price_std: '2461.53',
		unicode: 'U+1F1F8 U+1F1F3'
	},
	{
		code: 'SO',
		currency_code: 'SOS',
		currency_name: 'Somalia Shilling',
		currency_rate: 30.95956749,
		currency_symbol: 'S',
		emoji: '🇸🇴',
		id: "country:SO",
		name: 'Somalia',
		price_pro: '3095.96',
		price_std: '2321.97',
		unicode: 'U+1F1F8 U+1F1F4'
	},
	{
		code: 'SR',
		currency_code: 'SRD',
		currency_name: 'Suriname Dollar',
		currency_rate: 1.7512637,
		currency_symbol: '$',
		emoji: '🇸🇷',
		id: "country:SR",
		name: 'Suriname',
		price_pro: '175.13',
		price_std: '131.34',
		unicode: 'U+1F1F8 U+1F1F7'
	},
	{
		code: 'SS',
		currency_code: '',
		currency_name: '',
		currency_rate: 1,
		currency_symbol: '',
		emoji: '🇸🇸',
		id: "country:SS",
		name: 'South Sudan',
		price_pro: '100.00',
		price_std: '75.00',
		unicode: 'U+1F1F8 U+1F1F8'
	},
	{
		code: 'ST',
		currency_code: '',
		currency_name: '',
		currency_rate: 1,
		currency_symbol: '',
		emoji: '🇸🇹',
		id: "country:ST",
		name: 'São Tomé & Príncipe',
		price_pro: '100.00',
		price_std: '75.00',
		unicode: 'U+1F1F8 U+1F1F9'
	},
	{
		code: 'SV',
		currency_code: 'USD',
		currency_name: 'United States Dollar',
		currency_rate: 0.054288271,
		currency_symbol: '$',
		emoji: '🇸🇻',
		id: "country:SV",
		name: 'El Salvador',
		price_pro: '5.43',
		price_std: '4.07',
		unicode: 'U+1F1F8 U+1F1FB'
	},
	{
		code: 'SX',
		currency_code: 'ANG',
		currency_name: 'Netherlands Antilles Guilder',
		currency_rate: 0.09729635,
		currency_symbol: 'ƒ',
		emoji: '🇸🇽',
		id: "country:SX",
		name: 'Sint Maarten',
		price_pro: '9.73',
		price_std: '7.30',
		unicode: 'U+1F1F8 U+1F1FD'
	},
	{
		code: 'SY',
		currency_code: 'SYP',
		currency_name: 'Syria Pound',
		currency_rate: 705.84823288,
		currency_symbol: '£',
		emoji: '🇸🇾',
		id: "country:SY",
		name: 'Syria',
		price_pro: '70584.82',
		price_std: '52938.62',
		unicode: 'U+1F1F8 U+1F1FE'
	},
	{
		code: 'SZ',
		currency_code: '',
		currency_name: '',
		currency_rate: 1,
		currency_symbol: '',
		emoji: '🇸🇿',
		id: "country:SZ",
		name: 'Swaziland',
		price_pro: '100.00',
		price_std: '75.00',
		unicode: 'U+1F1F8 U+1F1FF'
	},
	{
		code: 'TA',
		currency_code: '?',
		currency_name: '?',
		currency_rate: 1,
		currency_symbol: '?',
		emoji: '🇹🇦',
		id: "country:TA",
		name: 'Tristan da Cunha',
		price_pro: '100.00',
		price_std: '75.00',
		unicode: 'U+1F1F9 U+1F1E6'
	},
	{
		code: 'TC',
		currency_code: 'USD',
		currency_name: 'United States Dollar',
		currency_rate: 0.054288271,
		currency_symbol: '$',
		emoji: '🇹🇨',
		id: "country:TC",
		name: 'Turks & Caicos Islands',
		price_pro: '5.43',
		price_std: '4.07',
		unicode: 'U+1F1F9 U+1F1E8'
	},
	{
		code: 'TD',
		currency_code: '',
		currency_name: '',
		currency_rate: 1,
		currency_symbol: '',
		emoji: '🇹🇩',
		id: "country:TD",
		name: 'Chad',
		price_pro: '100.00',
		price_std: '75.00',
		unicode: 'U+1F1F9 U+1F1E9'
	},
	{
		code: 'TF',
		currency_code: 'EUR',
		currency_name: 'Euro Member Countries',
		currency_rate: 0.050034445,
		currency_symbol: '€',
		emoji: '🇹🇫',
		id: "country:TF",
		name: 'French Southern Territories',
		price_pro: '5.00',
		price_std: '3.75',
		unicode: 'U+1F1F9 U+1F1EB'
	},
	{
		code: 'TG',
		currency_code: 'XOF',
		currency_name: 'West African CFA franc',
		currency_rate: 32.8204447,
		currency_symbol: 'F.CFA',
		emoji: '🇹🇬',
		id: "country:TG",
		name: 'Togo',
		price_pro: '3282.04',
		price_std: '2461.53',
		unicode: 'U+1F1F9 U+1F1EC'
	},
	{
		code: 'TH',
		currency_code: 'THB',
		currency_name: 'Thailand Baht',
		currency_rate: 1.9903729,
		currency_symbol: '฿',
		emoji: '🇹🇭',
		id: "country:TH",
		name: 'Thailand',
		price_pro: '199.04',
		price_std: '149.28',
		unicode: 'U+1F1F9 U+1F1ED'
	},
	{
		code: 'TJ',
		currency_code: '',
		currency_name: '',
		currency_rate: 1,
		currency_symbol: '',
		emoji: '🇹🇯',
		id: "country:TJ",
		name: 'Tajikistan',
		price_pro: '100.00',
		price_std: '75.00',
		unicode: 'U+1F1F9 U+1F1EF'
	},
	{
		code: 'TK',
		currency_code: 'NZD',
		currency_name: 'New Zealand Dollar',
		currency_rate: 0.088598209,
		currency_symbol: '$',
		emoji: '🇹🇰',
		id: "country:TK",
		name: 'Tokelau',
		price_pro: '8.86',
		price_std: '6.64',
		unicode: 'U+1F1F9 U+1F1F0'
	},
	{
		code: 'TL',
		currency_code: 'USD',
		currency_name: 'United States Dollar',
		currency_rate: 0.054288271,
		currency_symbol: '$',
		emoji: '🇹🇱',
		id: "country:TL",
		name: 'Timor-Leste',
		price_pro: '5.43',
		price_std: '4.07',
		unicode: 'U+1F1F9 U+1F1F1'
	},
	{
		code: 'TM',
		currency_code: '',
		currency_name: '',
		currency_rate: 1,
		currency_symbol: '',
		emoji: '🇹🇲',
		id: "country:TM",
		name: 'Turkmenistan',
		price_pro: '100.00',
		price_std: '75.00',
		unicode: 'U+1F1F9 U+1F1F2'
	},
	{
		code: 'TN',
		currency_code: '',
		currency_name: '',
		currency_rate: 1,
		currency_symbol: '',
		emoji: '🇹🇳',
		id: "country:TN",
		name: 'Tunisia',
		price_pro: '100.00',
		price_std: '75.00',
		unicode: 'U+1F1F9 U+1F1F3'
	},
	{
		code: 'TO',
		currency_code: '',
		currency_name: '',
		currency_rate: 1,
		currency_symbol: '',
		emoji: '🇹🇴',
		id: "country:TO",
		name: 'Tonga',
		price_pro: '100.00',
		price_std: '75.00',
		unicode: 'U+1F1F9 U+1F1F4'
	},
	{
		code: 'TR',
		currency_code: 'TRY',
		currency_name: 'Turkey Lira',
		currency_rate: 1.74950646,
		currency_symbol: '₺',
		emoji: '🇹🇷',
		id: "country:TR",
		name: 'Turkey',
		price_pro: '174.95',
		price_std: '131.21',
		unicode: 'U+1F1F9 U+1F1F7'
	},
	{
		code: 'TT',
		currency_code: 'TTD',
		currency_name: 'Trinidad and Tobago Dollar',
		currency_rate: 0.36821152,
		currency_symbol: 'TT$',
		emoji: '🇹🇹',
		id: "country:TT",
		name: 'Trinidad & Tobago',
		price_pro: '36.82',
		price_std: '27.62',
		unicode: 'U+1F1F9 U+1F1F9'
	},
	{
		code: 'TV',
		currency_code: 'AUD',
		currency_name: 'Australia Dollar',
		currency_rate: 0.08186056,
		currency_symbol: '$',
		emoji: '🇹🇻',
		id: "country:TV",
		name: 'Tuvalu',
		price_pro: '8.19',
		price_std: '6.14',
		unicode: 'U+1F1F9 U+1F1FB'
	},
	{
		code: 'TW',
		currency_code: 'TWD',
		currency_name: 'Taiwan New Dollar',
		currency_rate: 1.74854034,
		currency_symbol: 'NT$',
		emoji: '🇹🇼',
		id: "country:TW",
		name: 'Taiwan',
		price_pro: '174.85',
		price_std: '131.14',
		unicode: 'U+1F1F9 U+1F1FC'
	},
	{
		code: 'TZ',
		currency_code: '',
		currency_name: '',
		currency_rate: 1,
		currency_symbol: '',
		emoji: '🇹🇿',
		id: "country:TZ",
		name: 'Tanzania',
		price_pro: '100.00',
		price_std: '75.00',
		unicode: 'U+1F1F9 U+1F1FF'
	},
	{
		code: 'UA',
		currency_code: 'UAH',
		currency_name: 'Ukraine Hryvnia',
		currency_rate: 2.17933819,
		currency_symbol: '₴',
		emoji: '🇺🇦',
		id: "country:UA",
		name: 'Ukraine',
		price_pro: '217.93',
		price_std: '163.45',
		unicode: 'U+1F1FA U+1F1E6'
	},
	{
		code: 'UG',
		currency_code: '',
		currency_name: '',
		currency_rate: 1,
		currency_symbol: '',
		emoji: '🇺🇬',
		id: "country:UG",
		name: 'Uganda',
		price_pro: '100.00',
		price_std: '75.00',
		unicode: 'U+1F1FA U+1F1EC'
	},
	{
		code: 'UM',
		currency_code: 'USD',
		currency_name: 'United States Dollar',
		currency_rate: 0.054288271,
		currency_symbol: '$',
		emoji: '🇺🇲',
		id: "country:UM",
		name: 'U.S. Outlying Islands',
		price_pro: '5.43',
		price_std: '4.07',
		unicode: 'U+1F1FA U+1F1F2'
	},
	{
		code: 'UN',
		currency_code: '?',
		currency_name: '?',
		currency_rate: 1,
		currency_symbol: '?',
		emoji: '🇺🇳',
		id: "country:UN",
		name: 'United Nations',
		price_pro: '100.00',
		price_std: '75.00',
		unicode: 'U+1F1FA U+1F1F3'
	},
	{
		code: 'US',
		currency_code: 'USD',
		currency_name: 'United States Dollar',
		currency_rate: 0.054288271,
		currency_symbol: '$',
		emoji: '🇺🇸',
		id: "country:US",
		name: 'United States',
		price_pro: '5.43',
		price_std: '4.07',
		unicode: 'U+1F1FA U+1F1F8'
	},
	{
		code: 'UY',
		currency_code: 'UYU',
		currency_name: 'Uruguay Peso',
		currency_rate: 2.08788305,
		currency_symbol: '$U',
		emoji: '🇺🇾',
		id: "country:UY",
		name: 'Uruguay',
		price_pro: '208.79',
		price_std: '156.59',
		unicode: 'U+1F1FA U+1F1FE'
	},
	{
		code: 'UZ',
		currency_code: 'UZS',
		currency_name: 'Uzbekistan Som',
		currency_rate: 687.2891784,
		currency_symbol: 'лв',
		emoji: '🇺🇿',
		id: "country:UZ",
		name: 'Uzbekistan',
		price_pro: '68728.92',
		price_std: '51546.69',
		unicode: 'U+1F1FA U+1F1FF'
	},
	{
		code: 'VA',
		currency_code: 'EUR',
		currency_name: 'Euro Member Countries',
		currency_rate: 0.050034445,
		currency_symbol: '€',
		emoji: '🇻🇦',
		id: "country:VA",
		name: 'Vatican City',
		price_pro: '5.00',
		price_std: '3.75',
		unicode: 'U+1F1FB U+1F1E6'
	},
	{
		code: 'VC',
		currency_code: 'XCD',
		currency_name: 'East Caribbean Dollar',
		currency_rate: 0.14666974,
		currency_symbol: '$',
		emoji: '🇻🇨',
		id: "country:VC",
		name: 'St. Vincent & Grenadines',
		price_pro: '14.67',
		price_std: '11.00',
		unicode: 'U+1F1FB U+1F1E8'
	},
	{
		code: 'VE',
		currency_code: '',
		currency_name: '',
		currency_rate: 1,
		currency_symbol: '',
		emoji: '🇻🇪',
		id: "country:VE",
		name: 'Venezuela',
		price_pro: '100.00',
		price_std: '75.00',
		unicode: 'U+1F1FB U+1F1EA'
	},
	{
		code: 'VG',
		currency_code: 'USD',
		currency_name: 'United States Dollar',
		currency_rate: 0.054288271,
		currency_symbol: '$',
		emoji: '🇻🇬',
		id: "country:VG",
		name: 'British Virgin Islands',
		price_pro: '5.43',
		price_std: '4.07',
		unicode: 'U+1F1FB U+1F1EC'
	},
	{
		code: 'VI',
		currency_code: 'USD',
		currency_name: 'United States Dollar',
		currency_rate: 0.054288271,
		currency_symbol: '$',
		emoji: '🇻🇮',
		id: "country:VI",
		name: 'U.S. Virgin Islands',
		price_pro: '5.43',
		price_std: '4.07',
		unicode: 'U+1F1FB U+1F1EE'
	},
	{
		code: 'VN',
		currency_code: 'VND',
		currency_name: 'Viet Nam Dong',
		currency_rate: 1386.97772567,
		currency_symbol: '₫',
		emoji: '🇻🇳',
		id: "country:VN",
		name: 'Vietnam',
		price_pro: '138697.77',
		price_std: '104023.33',
		unicode: 'U+1F1FB U+1F1F3'
	},
	{
		code: 'VU',
		currency_code: '',
		currency_name: '',
		currency_rate: 1,
		currency_symbol: '',
		emoji: '🇻🇺',
		id: "country:VU",
		name: 'Vanuatu',
		price_pro: '100.00',
		price_std: '75.00',
		unicode: 'U+1F1FB U+1F1FA'
	},
	{
		code: 'WF',
		currency_code: '',
		currency_name: '',
		currency_rate: 1,
		currency_symbol: '',
		emoji: '🇼🇫',
		id: "country:WF",
		name: 'Wallis & Futuna',
		price_pro: '100.00',
		price_std: '75.00',
		unicode: 'U+1F1FC U+1F1EB'
	},
	{
		code: 'WS',
		currency_code: '',
		currency_name: '',
		currency_rate: 1,
		currency_symbol: '',
		emoji: '🇼🇸',
		id: "country:WS",
		name: 'Samoa',
		price_pro: '100.00',
		price_std: '75.00',
		unicode: 'U+1F1FC U+1F1F8'
	},
	{
		code: 'XK',
		currency_code: 'EUR',
		currency_name: 'Euro Member Countries',
		currency_rate: 0.050034445,
		currency_symbol: '€',
		emoji: '🇽🇰',
		id: "country:XK",
		name: 'Kosovo',
		price_pro: '5.00',
		price_std: '3.75',
		unicode: 'U+1F1FD U+1F1F0'
	},
	{
		code: 'YE',
		currency_code: 'YER',
		currency_name: 'Yemen Rial',
		currency_rate: 13.58278024,
		currency_symbol: '﷼',
		emoji: '🇾🇪',
		id: "country:YE",
		name: 'Yemen',
		price_pro: '1358.28',
		price_std: '1018.71',
		unicode: 'U+1F1FE U+1F1EA'
	},
	{
		code: 'YT',
		currency_code: 'EUR',
		currency_name: 'Euro Member Countries',
		currency_rate: 0.050034445,
		currency_symbol: '€',
		emoji: '🇾🇹',
		id: "country:YT",
		name: 'Mayotte',
		price_pro: '5.00',
		price_std: '3.75',
		unicode: 'U+1F1FE U+1F1F9'
	},
	{
		code: 'ZA',
		currency_code: 'ZAR',
		currency_name: 'South Africa Rand',
		currency_rate: 1,
		currency_symbol: 'R',
		emoji: '🇿🇦',
		id: "country:ZA",
		name: 'South Africa',
		price_pro: '100.00',
		price_std: '75.00',
		unicode: 'U+1F1FF U+1F1E6'
	},
	{
		code: 'ZM',
		currency_code: '',
		currency_name: '',
		currency_rate: 1,
		currency_symbol: '',
		emoji: '🇿🇲',
		id: "country:ZM",
		name: 'Zambia',
		price_pro: '100.00',
		price_std: '75.00',
		unicode: 'U+1F1FF U+1F1F2'
	},
	{
		code: 'ZW',
		currency_code: '',
		currency_name: '',
		currency_rate: 1,
		currency_symbol: '',
		emoji: '🇿🇼',
		id: "country:ZW",
		name: 'Zimbabwe',
		price_pro: '100.00',
		price_std: '75.00',
		unicode: 'U+1F1FF U+1F1FC'
	}
]}