import { z } from "zod";

export const payfast_notify_schema = z.strictObject({
  m_payment_id: z.string(),
  pf_payment_id: z.string(),
  payment_status: z.string(),
  item_name: z.string(),
  item_description: z.string(),
  amount_gross: z.string(),
  amount_fee: z.string(),
  amount_net: z.string(),
  custom_str1: z.string(),
  custom_str2: z.string(),
  custom_str3: z.string(),
  custom_str4: z.string(),
  custom_str5: z.string(),
  custom_int1: z.string(),
  custom_int2: z.string(),
  custom_int3: z.string(),
  custom_int4: z.string(),
  custom_int5: z.string(),
  name_first: z.string(),
  name_last: z.string(),
  email_address: z.string(),
  merchant_id: z.string(),
  signature: z.string(),
  token: z.string().optional(),
  billing_date: z.string().optional(),
});
